project_name: kafka-perf

before:
  hooks:
    - go mod download

builds:
  - main: ./main.go
    binary: kafka-perf
    ldflags:
      - -X github.com/kishaningithub/kafka-perf/cmd.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

brews:
  - tap:
      owner: kishaningithub
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kishaningithub/kafka-perf
    description: Get performance metrics based on kafka events
    license: MIT

nfpms:
  -
    id: kafka-perf
    package_name: kafka-perf
    homepage: https://github.com/kishaningithub/kafka-perf
    description: Get performance metrics based on kafka events
    license: MIT
    formats:
      - apk
      - deb
      - rpm